package alps.java.api.StandardPASS.PassProcessModelElements.DataDescribingComponents.DataMappingFunctions;

import alps.java.api.StandardPASS.PassProcessModelElements.DataDescribingComponents.IDataMappingFunction;

public interface IDataMappingIncomingToLocal extends IDataMappingFunction {
}
