package alps.java.api.StandardPASS.PassProcessModelElements.InteractiondescribingComponents;

import alps.java.api.StandardPASS.PassProcessModelElements.IInteractionDescribingComponent;

public interface ISubjectExecutionMapping extends IInteractionDescribingComponent {
}
