package alps.java.api.StandardPASS.PassProcessModelElements.DataDescribingComponents.PayloadDescriptions;

import alps.java.api.StandardPASS.PassProcessModelElements.DataDescribingComponents.IPayloadDescription;

public interface IPayloadPhysicalObjectDescription extends IPayloadDescription {
}
